### ISSUE TITLE
$ drjekyll new starter (not work)

### ISSUE THREAD

**Issue by StartZeroGnu** [drjekyllthemes/drjekyll#1]
```
$ drjekyll new starter

drjekyll/0.1.1 on Ruby 2.3.1 (2016-04-26) [i686-linux]
drjekyll/0.1.1 on Ruby 2.3.1 (2016-04-26) [i686-linux]
GET https://github.com/drjekyllthemes/themes/raw/master/themes.yml
*** theme 'starter' not found; sorry
```

![02](https://cloud.githubusercontent.com/assets/22280286/19981327/d3c026c8-a201-11e6-998c-81965b2029cb.png)

**Comment by geraldb** [comment]
@StartZeroGnu  Thanks for trying and reporting. I've fixed the missing shortcut key (starter). Please update the drjekyll gem (e.g. 1.0.1+). It's now working again (as advertised). Also note: your theme also works e.g. try:

```
$ drjekyll new szflexblog
```

Cheers.
